sf:
  target: dev <- environment to default to
  outputs:
    dev: <- configuring a specific environment
      type: snowflake
      account: MUZAFER
      user: muzafer
      password: Muzafer8008
      role: SYSADMIN
      database: DEMO_DB
      warehouse: COMPUTE_WH
      schema: INFORMATION_SCHEMA
<<<<<<< HEAD
      threads: 2
=======
      threads: 2
>>>>>>> 3c11d54b450bd0af99629ecad3565419ba93e92e
